package com.beauty.entity;

// Generated 2015-7-25 16:15:27 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.beauty.annotation.Orderable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * BeautyResource generated by hbm2java
 */
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })
@Entity
@Table(name = "beauty_resource", catalog = "beauty")
public class BeautyResource extends BaseEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	// @JsonProperty("DT_RowId")
	private Long id;
	@JsonProperty("DT_RowId")
	private Long DT_RowId;
	@Orderable(columnName = "code")
	private String code;
	@Orderable(columnName = "name")
	private String name;
	@Orderable(columnName = "url")
	private String url;

	public BeautyResource() {
	}

	public BeautyResource(String code, String name, String url, String remark) {
		super();
		this.code = code;
		this.name = name;
		this.url = url;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the dT_RowId
	 */
	@Transient
	public Long getDT_RowId() {
		return DT_RowId;
	}

	/**
	 * @param dT_RowId
	 *            the dT_RowId to set
	 */
	public void setDT_RowId(Long dT_RowId) {
		DT_RowId = dT_RowId;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
