package com.beauty.entity;

// Generated 2015-7-25 16:15:27 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BeautyUserExtra generated by hbm2java
 */
@Entity
@Table(name = "beauty_user_extra", catalog = "beauty")
public class BeautyUserExtra extends BaseEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Long userId;
	private String qq;
	private String wxNo;
	private String address;
	private String favor;

	public BeautyUserExtra() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "qq", nullable = false, length = 20)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "wx_no", nullable = false, length = 50)
	public String getWxNo() {
		return this.wxNo;
	}

	public void setWxNo(String wxNo) {
		this.wxNo = wxNo;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "favor", nullable = false, length = 50)
	public String getFavor() {
		return this.favor;
	}

	public void setFavor(String favor) {
		this.favor = favor;
	}

}
