package com.beauty.entity;

// Generated 2015-8-11 20:04:10 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.beauty.annotation.Orderable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * BeautyTableConfig generated by hbm2java
 */
@JsonInclude(Include.NON_NULL)
@Entity
@Table(name = "beauty_table_config", catalog = "beauty")
public class BeautyTableConfig extends BaseEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	// @JsonProperty("DT_RowId")
	private Long id;
	@JsonProperty("DT_RowId")
	private Long DT_RowId;
	@Orderable(columnName = "table_name")
	private String tableName;
	@Orderable(columnName = "title")
	private String title;
	@Orderable(columnName = "data")
	private String data;
	@Orderable(columnName = "column_name")
	private String columnName;
	@Orderable(columnName = "orderable")
	private Byte orderable;
	@Orderable(columnName = "width")
	private Integer width;
	@Orderable(columnName = "class_name")
	private String className;
	@Orderable(columnName = "sequence")
	private Integer sequence;
	private String render;

	public BeautyTableConfig() {
	}

	public BeautyTableConfig(String tableName, String columnName) {
		super();
		this.tableName = tableName;
		this.columnName = columnName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the dT_RowId
	 */
	@Transient
	public Long getDT_RowId() {
		return DT_RowId;
	}

	/**
	 * @param dT_RowId
	 *            the dT_RowId to set
	 */
	public void setDT_RowId(Long dT_RowId) {
		DT_RowId = dT_RowId;
	}

	@Column(name = "table_name", nullable = false, length = 50)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "title", nullable = false, length = 50, insertable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "data", nullable = false, length = 50, insertable = false)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "column_name", nullable = false, length = 50)
	public String getColumnName() {
		return columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "orderable", nullable = false)
	public Byte getOrderable() {
		return this.orderable;
	}

	public void setOrderable(Byte orderable) {
		this.orderable = orderable;
	}

	@Column(name = "width", nullable = false)
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "class_name", nullable = false, length = 50, insertable = false)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "sequence", nullable = false)
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	@Column(name = "render", nullable = false, length = 100, insertable = false)
	public String getRender() {
		return this.render;
	}

	public void setRender(String render) {
		this.render = render;
	}

}
