package com.beauty.entity;

// Generated 2015-7-25 16:15:27 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.beauty.annotation.Orderable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * BeautyMenu generated by hbm2java
 */
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "children" })
@JsonInclude(Include.NON_NULL)
@Entity
@Table(name = "beauty_menu", catalog = "beauty")
public class BeautyMenu extends BaseEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	@Orderable(columnName = "code")
	private String code;
	@Orderable(columnName = "name")
	private String name;
	@Orderable(columnName = "url")
	private String url;
	private Long parentId;
	private Byte level;

	private List<BeautyMenu> children = new ArrayList<BeautyMenu>();

	public BeautyMenu() {
	}

	public void reset(String searchValue) {
		this.code = searchValue;
		this.name = searchValue;
		this.url = searchValue;
		this.remark = searchValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code == null ? null : this.code.toUpperCase();
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "parent_id", nullable = false)
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "level", nullable = false, updatable = false, insertable = false)
	public Byte getLevel() {
		return this.level;
	}

	public void setLevel(Byte level) {
		this.level = level;
	}

	/**
	 * @return the children
	 */
	@Transient
	public List<BeautyMenu> getChildren() {
		return children;
	}

	/**
	 * @param children
	 *            the children to set
	 */
	public void setChildren(List<BeautyMenu> children) {
		this.children = children;
	}

}
