package com.beauty.sys.entity;

// Generated 2015-7-25 16:15:27 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BeautyRoleAuthority generated by hbm2java
 */
@Entity
@Table(name = "beauty_role_authority", catalog = "beauty")
public class BeautyRoleAuthority implements java.io.Serializable {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private long roleId;
	private long authorityId;

	public BeautyRoleAuthority() {
	}

	public BeautyRoleAuthority(long roleId, long authorityId) {
		this.roleId = roleId;
		this.authorityId = authorityId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "role_id", nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "authority_id", nullable = false)
	public long getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(long authorityId) {
		this.authorityId = authorityId;
	}

}
