package com.beauty.sys.entity;

public class SysColumns {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.TABLE_CATALOG
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String tableCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.TABLE_SCHEMA
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String tableSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.TABLE_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLUMN_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.ORDINAL_POSITION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private Long ordinalPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.IS_NULLABLE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String isNullable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.DATA_TYPE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private Long characterMaximumLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private Long characterOctetLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.NUMERIC_PRECISION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private Long numericPrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.NUMERIC_SCALE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private Long numericScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.DATETIME_PRECISION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private Long datetimePrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.CHARACTER_SET_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String characterSetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLLATION_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String collationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLUMN_KEY
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String columnKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.EXTRA
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.PRIVILEGES
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String privileges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLUMN_COMMENT
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    private String columnComment;
    
    
    private String columnType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.TABLE_CATALOG
     *
     * @return the value of COLUMNS.TABLE_CATALOG
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.TABLE_CATALOG
     *
     * @param tableCatalog the value for COLUMNS.TABLE_CATALOG
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog == null ? null : tableCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.TABLE_SCHEMA
     *
     * @return the value of COLUMNS.TABLE_SCHEMA
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.TABLE_SCHEMA
     *
     * @param tableSchema the value for COLUMNS.TABLE_SCHEMA
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema == null ? null : tableSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.TABLE_NAME
     *
     * @return the value of COLUMNS.TABLE_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.TABLE_NAME
     *
     * @param tableName the value for COLUMNS.TABLE_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLUMN_NAME
     *
     * @return the value of COLUMNS.COLUMN_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLUMN_NAME
     *
     * @param columnName the value for COLUMNS.COLUMN_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.ORDINAL_POSITION
     *
     * @return the value of COLUMNS.ORDINAL_POSITION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public Long getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.ORDINAL_POSITION
     *
     * @param ordinalPosition the value for COLUMNS.ORDINAL_POSITION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setOrdinalPosition(Long ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.IS_NULLABLE
     *
     * @return the value of COLUMNS.IS_NULLABLE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getIsNullable() {
        return isNullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.IS_NULLABLE
     *
     * @param isNullable the value for COLUMNS.IS_NULLABLE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setIsNullable(String isNullable) {
        this.isNullable = isNullable == null ? null : isNullable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.DATA_TYPE
     *
     * @return the value of COLUMNS.DATA_TYPE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.DATA_TYPE
     *
     * @param dataType the value for COLUMNS.DATA_TYPE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @return the value of COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public Long getCharacterMaximumLength() {
        return characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @param characterMaximumLength the value for COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setCharacterMaximumLength(Long characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @return the value of COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public Long getCharacterOctetLength() {
        return characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @param characterOctetLength the value for COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setCharacterOctetLength(Long characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.NUMERIC_PRECISION
     *
     * @return the value of COLUMNS.NUMERIC_PRECISION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public Long getNumericPrecision() {
        return numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.NUMERIC_PRECISION
     *
     * @param numericPrecision the value for COLUMNS.NUMERIC_PRECISION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setNumericPrecision(Long numericPrecision) {
        this.numericPrecision = numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.NUMERIC_SCALE
     *
     * @return the value of COLUMNS.NUMERIC_SCALE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public Long getNumericScale() {
        return numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.NUMERIC_SCALE
     *
     * @param numericScale the value for COLUMNS.NUMERIC_SCALE
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setNumericScale(Long numericScale) {
        this.numericScale = numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.DATETIME_PRECISION
     *
     * @return the value of COLUMNS.DATETIME_PRECISION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public Long getDatetimePrecision() {
        return datetimePrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.DATETIME_PRECISION
     *
     * @param datetimePrecision the value for COLUMNS.DATETIME_PRECISION
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setDatetimePrecision(Long datetimePrecision) {
        this.datetimePrecision = datetimePrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.CHARACTER_SET_NAME
     *
     * @return the value of COLUMNS.CHARACTER_SET_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.CHARACTER_SET_NAME
     *
     * @param characterSetName the value for COLUMNS.CHARACTER_SET_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName == null ? null : characterSetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLLATION_NAME
     *
     * @return the value of COLUMNS.COLLATION_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getCollationName() {
        return collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLLATION_NAME
     *
     * @param collationName the value for COLUMNS.COLLATION_NAME
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setCollationName(String collationName) {
        this.collationName = collationName == null ? null : collationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLUMN_KEY
     *
     * @return the value of COLUMNS.COLUMN_KEY
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getColumnKey() {
        return columnKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLUMN_KEY
     *
     * @param columnKey the value for COLUMNS.COLUMN_KEY
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setColumnKey(String columnKey) {
        this.columnKey = columnKey == null ? null : columnKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.EXTRA
     *
     * @return the value of COLUMNS.EXTRA
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.EXTRA
     *
     * @param extra the value for COLUMNS.EXTRA
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.PRIVILEGES
     *
     * @return the value of COLUMNS.PRIVILEGES
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getPrivileges() {
        return privileges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.PRIVILEGES
     *
     * @param privileges the value for COLUMNS.PRIVILEGES
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setPrivileges(String privileges) {
        this.privileges = privileges == null ? null : privileges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLUMN_COMMENT
     *
     * @return the value of COLUMNS.COLUMN_COMMENT
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public String getColumnComment() {
        return columnComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLUMN_COMMENT
     *
     * @param columnComment the value for COLUMNS.COLUMN_COMMENT
     *
     * @mbggenerated Tue Aug 11 22:40:48 CST 2015
     */
    public void setColumnComment(String columnComment) {
        this.columnComment = columnComment == null ? null : columnComment.trim();
    }

	/**
	 * @return the columnType
	 */
	public String getColumnType() {
		return columnType;
	}

	/**
	 * @param columnType the columnType to set
	 */
	public void setColumnType(String columnType) {
		this.columnType = columnType == null ? null : columnType.trim();
	}
    
    
}